### ISSUE TITLE
Configuration issue on Ubuntu 16.10

### ISSUE THREAD

**Issue by sjunges** [smtrat/carl#8] opened 2017-05-11 18:17 UTC
On Ubuntu 16.10, I get the following error message during configuration.

-- The CXX compiler identification is GNU 6.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using g++ 6.2.0
-- CXX Flags:  -std=c++14 -Wunknown-pragmas -fmax-errors=5 -fdiagnostics-color=auto
-- CXX Debug Flags:  -O1
-- CXX Release Flags:  -O3
-- Build type: 
-- Building static: no
-- not using cotire
-- Use system version of GMP/GMPXX 6.1.1
-- Library Boost was not found.
-- Use shipped version of Boost 1.60.0
-- Use system version of Eigen3 3.2.93
-- Use shipped version of GTest 1.8.0
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Could NOT find LATEX (missing:  LATEX_COMPILER) 
-- Did not find clang-tidy, target tidy is disabled.
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Registered with cmake
CMake Error at cmake/carlmacros.cmake:67 (get_target_property):
  get_target_property() called with non-existent target "Boost_SHARED".
Call Stack (most recent call first):
  cmake/carlmacros.cmake:88 (export_target)
  cmake/export.cmake:32 (export_target_recursive)
  CMakeLists.txt:183 (include)

CMake Error at cmake/carlmacros.cmake:67 (get_target_property):
  get_target_property() called with non-existent target "Boost_STATIC".
Call Stack (most recent call first):
  cmake/carlmacros.cmake:88 (export_target)
  cmake/export.cmake:33 (export_target_recursive)
  CMakeLists.txt:183 (include)

-- Configuring incomplete, errors occurred!
See also "/home/sebastian/i2/carl/build/CMakeFiles/CMakeOutput.log".

**Comment by sjunges** [comment] 2017-05-11 20:35
In particular, -- Library Boost was not found is interesting, as Boost 1.62 is installed.

**Comment by RaoulSchaffranek** [comment] 2017-05-16 13:50
I witness the same behavior with Ubuntu 14.04.

<details>
   <summary>Stacktrace</summary>
<pre>bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant/carl/build$ cmake ../
-- Using g++ 6.2.0
-- CXX Flags:  -std=c++14 -Wunknown-pragmas -fmax-errors=5 -fdiagnostics-color=auto
-- CXX Debug Flags:  -O1
-- CXX Release Flags:  -O3
-- Build type:
-- Building static: no
-- not using cotire
-- Use system version of GMP/GMPXX 5.1.3
-- Library Boost was not found.
-- Use shipped version of Boost 1.60.0
-- Use system version of Eigen3 3.2.0
-- Use shipped version of GTest 1.8.0
-- Did not find clang-tidy, target tidy is disabled.
-- Registered with cmake
CMake Error at cmake/carlmacros.cmake:67 (get_target_property):
  get_target_property() called with non-existent target "Boost_SHARED".
Call Stack (most recent call first):
  cmake/carlmacros.cmake:88 (export_target)
  cmake/export.cmake:32 (export_target_recursive)
  CMakeLists.txt:183 (include)


CMake Error at cmake/carlmacros.cmake:67 (get_target_property):
  get_target_property() called with non-existent target "Boost_STATIC".
Call Stack (most recent call first):
  cmake/carlmacros.cmake:88 (export_target)
  cmake/export.cmake:33 (export_target_recursive)
  CMakeLists.txt:183 (include)


-- Configuring incomplete, errors occurred!
See also "/vagrant/carl/build/CMakeFiles/CMakeOutput.log".</pre>
</details>

However, it still works with bfb8ea2

**Comment by nafur** [comment] 2017-05-16 14:19
Ah, I finally realized what the problem is: the script that builds boost if it is not found in the system did not create the targets that we now assume exist. 6584e099 should be a (provisional) fix to this. Obviously, the boost libs that are imported at [resources.cmake](https://github.com/smtrat/carl/blob/master/resources/resources.cmake#L35) should also be imported in boost.cmake

**Comment by RaoulSchaffranek** [comment] 2017-05-16 14:52
Hi, thanks for the help. Unfortunately, this doesn't fix the issue for me - the error-message stays the same.

**Comment by nafur** [comment] 2017-05-24 19:57
I assume that this is fixed (like smtrat/smtrat#6)?

**Comment by RaoulSchaffranek** [comment] 2017-05-28 13:36
Not really, we just hard-coded the path to the boost-directly in cmake.

**Comment by nafur** [comment] 2017-05-29 07:34
So you still have this error, if it is not hard-coded?

**Comment by smtrat** [comment] 2017-07-18 14:18
I assume this is fixed by now.

**Closed by smtrat** 2017-07-18 14:18 UTC
