### ISSUE TITLE
Build fails with GCC (6.3) on MacOSX

### ISSUE THREAD

**Issue by tjanson** [smtrat/carl#6] opened 2017-04-11 17:08 UTC
Both current master `5ac580c` and tag `17.04` fail to build with GCC 6.3 on my macOS 10.11 machine, with error:

```
Undefined symbols for architecture x86_64:
  "operator<<(std::basic_ostream<char, std::char_traits<char> >&, __mpq_struct const*)"
```

[Full log available here.](https://gist.github.com/tjanson/f40afb54ae5f10923dc8242886baaacc#file-cmake-build-target-lib_carl-log-L37-L45)

Using clang, it works without problems.

**Comment by smtrat** [comment] 2017-04-12 07:36
Let's have a look at
``operator<<(std::basic_ostream<char, std::char_traits<char> >&, __mpq_struct const*)``
``std::basic_ostream<char, std::char_traits<char> >& operator<< <__mpq_struct [1], __mpq_struct [1]>(std::basic_ostream<char, std::char_traits<char> >&, __gmp_expr<__mpq_struct [1], __mpq_struct [1]> const&)``

It seems to me that the first one is the gmp operator while the second one is the gmpxx operator. Can you check whether the linking order is wrong? (gmpxx should be before gmp, though I have no idea why it would make a difference if you use clang instead)

**Comment by tjanson** [comment] 2017-04-15 17:02
> Can you check whether the linking order is wrong?

The [output of `VERBOSE=1 make lib_carl`](https://gist.github.com/tjanson/f40afb54ae5f10923dc8242886baaacc#file-verbose-1-cmake-build-target-lib_carl-L16) lists `libgmpxx.dylib` last, after `libgmp.dylib` (at the very end of the highlighted line).

I tried switching the order by modifying `build/src/carl/CMakeFiles/lib_carl.dir/link.txt` accordingly and then executed the failed call again (`cmake -E cmake_link_script CMakeFiles/lib_carl.dir/link.txt --verbose=1`) but the result was in fact the same.
I don’t know whether that attempt was too naive or whether this indicates that the problem lies elsewhere.

FYI I’m not actually trying to build Carl with GCC for my own use, I just noticed this while having trouble with Storm and GCC.

**Comment by smtrat** [comment] 2017-04-24 11:03
Well, this actually looks like a carl bug. However I wonder why it does not affect other compilers...
Could you change the order at https://github.com/smtrat/carl/blob/master/src/carl/CMakeLists.txt#L30 and check whether it fixes your issue?

**Comment by smtrat** [comment] 2017-05-01 12:03
I tried this with 7ac1d7e8 but it still fails (see https://travis-ci.org/smtrat/carl/jobs/227553730).
Furthermore, it also affects cln (at least on travis) which should be self-contained in a single library.

Any ideas?

**Comment by nafur** [comment] 2017-05-21 12:39
Okay, I dived into this yesterday. The problem is the following:
libgmp (and libcln) are build with clang and the symbol for `operator<<(...)` use `std::__1::ostream`.
gcc however uses `std::ostream` and thus these symbols do not match when we try to link `lib_carl`.
See https://travis-ci.org/nafur/carl_debug for some debugging builds on this.

We have basically two possibilities: either make gcc use the clang stdlib or patch the libraries so that the symbols coincide. I investigated the latter.

You can use `objcopy` to rename symbols. MacOS' `objcopy` can't do this, but you can install `gobjcopy` which I tried to use at https://github.com/nafur/carl_debug/blob/master/src/carl/CMakeLists.txt#L31. This however changes the architecture in some way: https://travis-ci.org/nafur/carl_debug/jobs/234185710#L2294
The only possible workaround I could find is using `sed` instead of `objcopy`: http://www.witwolf.cc/archives/62.html
At this point, I stopped investigating this...

I know we made clang use gcc's stdlib at some point, but not the other way round. Is this possible?

**Comment by tjanson** [comment] 2017-05-22 00:56
I don’t blame you for not trying to follow a blog post written in Chinese. ;) As for your question, I’m pretty clueless about the whole standard library thing. StackOverflow has [this possible (hacky? working?) solution](https://stackoverflow.com/questions/22228208/using-g-with-libc) as well as [a good description without a solution](https://stackoverflow.com/questions/12542971/using-libstdc-compiled-libraries-with-clang-stdlib-libc).

Again, I’m not actually interested in using GCC, so don’t put time into this in for my sake only. (But I’ve encountered the same issue in some other projects now, so I am curious about a possible solution.)

**Comment by smtrat** [comment] 2019-01-29 09:07
Closing as GCC6 is not supported anymore.

**Closed by smtrat** 2019-01-29 09:07 UTC
Labels: bug, help wanted
